import Header from '@/components/Header/Header'
import Sidebar from '@/components/Sidebar/Sidebar'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

import './globals.css'
import { Provider } from './provider'

const poppinsSm = Poppins({ subsets: ['latin'], weight: '500' })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={poppinsSm.className}>
				<Provider>
					<div className='flex relative bg-gray-100'>
						<Sidebar />
						<div className='absolute left-[80px] md:left-[150px] lg:left-[230px] xl:left-[250px] right-0'>
							<Header />
							<div>{children}</div>
						</div>
					</div>
				</Provider>
			</body>
		</html>
	)
}
